#index:
#    path: /
#    controller: App\Controller\DefaultController::index

error404:
    path: /{wildcard}
    controller: 'App\Controller\ErrorController::error404'
    requirements:
        wildcard: ".*"
